#! /usr/bin/env bash


if [ ! -d ~/.sdkman ] ; then
   echo 'installing SDKMAN'
   curl -s "https://get.sdkman.io" | bash
   echo "OPEN A NEW SHELL, SDKMAN-INIT IS SOURCED FROM BASHRC.BASH"
   echo "THEN RUN ME AGAIN"
   exit
fi

# sdk is a function, so we aren't going to inherit it, must re-import:
echo "sourcing sdkman-init"
source "/Users/$(whoami)/.sdkman/bin/sdkman-init.sh"

set -o errexit
set -o pipefail
set -o nounset

echo "TODO: sdk install not working from within script"
echo "TODO: sorry, you'll need to run the commands one-by-one manually"
exit

echo "installing 11.0.2-open"
sdk install java 11.0.2-open

echo "installing gradle 4.10.2"
sdk install gradle 4.10.2

echo "installing groovy 2.4.7"
sdk install groovy 2.4.7

if [ -d /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/ ]; then
  # have to install this from the JDK installer:
  echo "installing java 1.8.0_181"
  sdk install java 1.8.0_181 /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/
fi

